### ISSUE TITLE
Unhandled ClipboardWatcher exception

### ISSUE THREAD

**Issue by cdiamon** [StefanLobbenmeier/youtube-dl-gui#40]
**Describe the bug**
Every time I copy any text, the app shows the error

`A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Object has been destroyed
at ClipboardWatcher.resetPlaceholder (/Applications/Open Video Downloader.app/Contents/Resources/app.asar/modules/ClipboardWatcher.js:18:22)
at ClipboardWatcher.poll (/Applications/Open Video Downloader.app/Contents/Resources/app.asar/modules/ClipboardWatcher.js:34:26)
at Timeout._onTimeout (/Applications/Open Video Downloader.app/Contents/Resources/app.asar/modules/ClipboardWatcher.js:12:46)
at listOnTimeout (internal/timers.js:549:17)
at processTimers (internal/timers.js:492:7)`

**To Reproduce**
- App is opened
- Copy any text

**Expected behavior**
paste an URL inside the app or ignore the exception

**Screenshots**
<img width="795" alt="image" src="https://user-images.githubusercontent.com/17109566/223699641-76e7fd41-f499-41a8-a925-219697f7e276.png">

**Additional info (please complete the following information):**
 - macOS 13.2.1 (22D68) M1 Pro
 - Application version 2.4.8

**Comment by StefanLobbenmeier** [comment]
Yeah I have seen that on macOS as well. Will need to investigate how to handle it
