### ISSUE TITLE
Playlist Index Not Working or Inconsistent

### ISSUE THREAD

**Issue by mnasty** [StefanLobbenmeier/youtube-dl-gui#99]
**Describe the bug**
The playlist index function provided by the underlying yt-dlp program that is set by going into the preferences under 'Filename format:' does not work for all playlists. The value is left empty on certain playlists, particularly those of longer length or with missing/unavailable videos.

**To Reproduce**
1. Set the following settings:

- Audio Only / Best Quality
- Set a download path (Documents/test or whatever)
- Max concurrent jobs = 32
- Force audio only downloads to use following format = MP3
- Filename format: Custom = %(playlist_index)s-%(title).200s.%(ext)s

2.) Add this playlist to queue:
https://youtube.com/playlist?list=PL8qx-4ZyzJYVVndghoKJ6DCIHWkZD0lZG&si=B8nLFJix_fCnT45q

3.) Download the playlist

**Expected behavior**
Filename in the downloaded files matches the format consistently without missing information.

Example:
7-3AM.mp3 **NOT** -3AM.mp3 

**Additional info (please complete the following information):**
 - OS: MacOS 14.1.2 Sonoma
 - Application version: 2.5.4
 - Application type: Downloaded from releases and built from source w/ electron

**Additional context**
This appears to be a recurring issue that has been mentioned multiple times in both the original and most current versions of this application repository under GitHub issues. I will link all the relevant issues I can find.

I have located and solved for the root cause and will provide a pull request with the solution that appears to work consistently for many types of playlists and passes all tests except those that appear to have nothing to do with the changes I made. Just a few simple errors that are buried in a mess of an uncommented and heavily abstracted codebase.

The test failures were probably introduced when fixing the binary downloading process from the base repo when the tests were not updated to match the new code, even though the process is working just fine (see below)

```
TypeError: process.getSystemVersion is not a function
    at BinaryUpdater.getSystemVersion (/Users/mick/dev/web/ytdl-fix/modules/BinaryUpdater.js:99:42)
    at BinaryUpdater.getBinaryUrl (/Users/mick/dev/web/ytdl-fix/modules/BinaryUpdater.js:85:38)
    at BinaryUpdater.checkUpdate (/Users/mick/dev/web/ytdl-fix/modules/BinaryUpdater.js:34:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by mnasty** [comment]
Linking #9

**Comment by StefanLobbenmeier** [comment]
I always thought that the issue is that open video download flattens the playlist / it creates a video per playlist entry, and in this step the playlist information is lost.

**Comment by StefanLobbenmeier** [comment]
Oh I see, there is already a Manual workaround for this: https://github.com/jely2002/youtube-dl-gui/issues/97#issuecomment-855311037

while I don’t agree with the approach (I would like yt-dlp handle it itself) it seems your fix just fixed the workaround here.

**Comment by StefanLobbenmeier** [comment]
This was fixed with https://github.com/StefanLobbenmeier/youtube-dl-gui/issues/99

**Comment by zlrss17** [comment]
> This was fixed with [#99](https://github.com/StefanLobbenmeier/youtube-dl-gui/issues/99), but I missed to release it

Please man, I can't build package by myself. Thanks for advance.

**Comment by StefanLobbenmeier** [comment]
Didn’t have the time this weekend, but have a reminder to release next weekend 😄
